### ISSUE TITLE
OSError - Cannot load native module in Linux

### ISSUE THREAD

**Issue by harik8** [BraydenNeale/Dynatrace-SNMP#15]
Hi @BraydenNeale 

I got `raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))` when running `custom_snmp_base_plugin_remote.py `. I have attached the stack trace. 

```
$ python3 custom_snmp_base_plugin_remote.py 
Traceback (most recent call last):
  File "custom_snmp_base_plugin_remote.py", line 6, in <module>
    from dtsnmp.host_resource_mib import HostResourceMIB
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/dtsnmp/host_resource_mib.py", line 2, in <module>
    from .poller import Poller
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/dtsnmp/poller.py", line 2, in <module>
    from pysnmp.hlapi import *
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/pysnmp/hlapi/__init__.py", line 10, in <module>
    from pysnmp.hlapi import auth
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/pysnmp/hlapi/auth.py", line 7, in <module>
    from pysnmp.entity import config
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/pysnmp/entity/config.py", line 9, in <module>
    from pysnmp.proto.secmod.rfc3414.auth import hmacmd5, hmacsha, noauth
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/pysnmp/proto/secmod/rfc3414/__init__.py", line 7, in <module>
    from pysnmp.proto.secmod.rfc3414 import service
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/pysnmp/proto/secmod/rfc3414/service.py", line 11, in <module>
    from pysnmp.proto.secmod.rfc3414.priv import des, nopriv
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/pysnmp/proto/secmod/rfc3414/priv/des.py", line 17, in <module>
    from Cryptodome.Cipher import DES
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/Cryptodome/Cipher/_mode_ecb.py", line 47, in <module>
    """
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/Cryptodome/Util/_raw_api.py", line 299, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.cpython-37m-x86_64-linux-gnu.so': /opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/Cryptodome/Util/../Cipher/_raw_ecb.cpython-37m-x86_64-linux-gnu.so
: cannot open shared object file: No such file or directory, Trying '_raw_ecb.abi3.so': /opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or di
rectory, Trying '_raw_ecb.so': /opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.snmp-base/Cryptodome/Util/../Cipher/_raw_ecb.so: cannot open shared object file: No such file or directory
---
$ uname -a
Linux ip-10-100-135-120.eu-west-1.compute.internal 4.14.231-173.361.amzn2.x86_64 #1 SMP Mon Apr 26 20:57:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by BraydenNeale** [comment]
Hi @harik8 

Can you try running this with python 3.6 (that's what comes bundled in with the Dynatrace ActiveGate remote plugin module).
From the trace it looks like you are running python 3.7 - raw_ecb.cpython-37m-x86_64-linux-gnu.so.
It may be trying to reference a cipher module which isn't available.

Also, Dynatrace are releasing official support for SNMP monitoring :). I'll be updating this repo to point to that in future.
https://www.dynatrace.com/news/blog/simplified-observability-for-your-snmp-devices/
https://www.dynatrace.com/support/help/extend-dynatrace/extensions20/snmp-extensions/
